name: CI (Code Quality & Tests)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  quality-and-tests:
    name: Rust Audit, Lint and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt

    - name: Enable Rust Caching
      uses: Swatinem/rust-cache@v2

    - name: Check code formatting
      run: cargo fmt --check

    - name: Run Clippy (Linter)
      run: cargo clippy -- -D warnings

    - name: Run integration and unit tests
      run: cargo test --verbose
